// Regenerates the KU WBB launcher icon. Run from a directory with
// playwright installed:  node scripts/make-icons.mjs app/src/main/res
// Generates the launcher icon: adaptive-icon vector drawables plus legacy
// raster webp for API 24-25 (minSdk is 24, below adaptive icons).
// Rasterizing goes through Chromium's canvas, which can encode webp, so the
// existing .webp filenames stay put and no resource renames are needed.
//
// The mark itself lives in icon-art.mjs, shared with make-web-icons.mjs.
import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';
import { svgIcon, SEAMS, circlePath, KU_BLUE, BALL, SEAM, R, SW } from './icon-art.mjs';

const RES = process.argv[2] || '/home/user/ku-wbb/app/src/main/res';

// --- Vector drawables -------------------------------------------------------
const seamPaths = (color) => SEAMS.map((d) =>
  `    <path
        android:pathData="${d}"
        android:strokeColor="${color}"
        android:strokeWidth="${SW}"
        android:strokeLineCap="round" />`).join('\n');

const vector = (body) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/make-icons.mjs — edit that, not this. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
${body}
</vector>
`;

const foreground = vector(
  `    <path
        android:pathData="${circlePath(R)}"
        android:fillColor="${BALL}" />
${seamPaths(SEAM)}`
);

const background = vector(
  `    <path
        android:pathData="M0,0h108v108h-108z"
        android:fillColor="${KU_BLUE}" />`
);

// Themed icons (Android 13+) are tinted by the system, so a filled disc would
// flatten into a blob — line art keeps the ball readable.
const monochrome = vector(
  `    <path
        android:pathData="${circlePath(R - SW / 2)}"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="${SW}" />
${seamPaths('#FFFFFF')}`
);

fs.writeFileSync(path.join(RES, 'drawable/ic_launcher_foreground.xml'), foreground);
fs.writeFileSync(path.join(RES, 'drawable/ic_launcher_background.xml'), background);
fs.writeFileSync(path.join(RES, 'drawable/ic_launcher_monochrome.xml'), monochrome);
console.log('wrote 3 vector drawables');

// --- Legacy raster ----------------------------------------------------------
const svg = (shape) => svgIcon(shape);

const DENSITIES = { mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 };
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage();
await page.setContent('<body style="margin:0"></body>');

for (const [density, size] of Object.entries(DENSITIES)) {
  for (const [file, shape] of [['ic_launcher', 'square'], ['ic_launcher_round', 'round']]) {
    const b64 = await page.evaluate(async ({ markup, size }) => {
      const img = new Image();
      img.src = 'data:image/svg+xml;base64,' + btoa(markup);
      await img.decode();
      const cv = document.createElement('canvas');
      cv.width = cv.height = size;
      const ctx = cv.getContext('2d');
      ctx.drawImage(img, 0, 0, size, size);
      return cv.toDataURL('image/webp', 0.98).split(',')[1];
    }, { markup: svg(shape), size });
    const out = path.join(RES, `mipmap-${density}/${file}.webp`);
    const buf = Buffer.from(b64, 'base64');
    // Guard against a silent PNG fallback if webp encoding were unavailable.
    if (buf.slice(8, 12).toString() !== 'WEBP') throw new Error(`not webp: ${out}`);
    fs.writeFileSync(out, buf);
    console.log(`wrote ${out} (${size}px, ${buf.length}b)`);
  }
}
await browser.close();

// Preview sheet so the result can be eyeballed at real sizes.
const PREVIEW = process.env.PREVIEW_PATH || '/tmp/icon-preview.html';
fs.writeFileSync(PREVIEW,
  `<body style="background:#2a2a2a;padding:20px;font:12px sans-serif;color:#ddd">
   <div style="display:flex;gap:20px;align-items:flex-end;flex-wrap:wrap">
   ${Object.entries(DENSITIES).map(([d, s]) =>
    `<figure style="margin:0;text-align:center"><div style="width:${s}px">${svg('square')
      .replace('width="108" height="108"', `width="${s}" height="${s}"`)}</div>
      <figcaption>${d} ${s}px</figcaption></figure>`).join('')}
   ${Object.entries(DENSITIES).map(([d, s]) =>
    `<figure style="margin:0;text-align:center"><div style="width:${s}px">${svg('round')
      .replace('width="108" height="108"', `width="${s}" height="${s}"`)}</div>
      <figcaption>${d} round</figcaption></figure>`).join('')}
   </div></body>`);
console.log('wrote preview sheet to ' + PREVIEW);
